# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [11]:
import numpy as np
arr = np.random.uniform(0, 20,28)
arr = arr.reshape((4,7))
minim = np.min(arr)
maxim = np.max(arr)
print(arr)
print("-----")
print(np.around((arr-minim)/(maxim-minim), decimals=1))

[[11.74742914 19.48171181  7.13413335  9.00020073  2.02513711 11.79018952
   2.50132628]
 [ 8.00840088 10.45272522  0.08654066 14.8756075   1.27362354  3.99739531
   9.4083515 ]
 [11.0716098  18.78947409  7.40857018 12.02364357  9.3431472  10.49646523
   9.15575024]
 [ 9.21876907  4.64951776 18.58523825  8.04169855  7.91838156  5.82461772
  11.30094345]]
-----
[[0.6 1.  0.4 0.5 0.1 0.6 0.1]
 [0.4 0.5 0.  0.8 0.1 0.2 0.5]
 [0.6 1.  0.4 0.6 0.5 0.5 0.5]
 [0.5 0.2 1.  0.4 0.4 0.3 0.6]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [8]:
import numpy as np
arr = np.random.randint(0, 10, 80)
arr = arr.reshape(8, 10)
k = 0
minim = 10000
for i in range(len(arr)):
  if sum(arr[i]) <minim:
    minim = sum(arr[i])
    k = i
print(arr)
print("----")
print(f'Индекс {k}\nСтрока {arr[i]}')

[[5 0 1 9 3 2 7 6 9 5]
 [8 0 1 9 0 7 8 3 3 0]
 [0 7 8 8 3 5 8 7 4 0]
 [2 4 2 1 6 2 1 9 6 3]
 [6 1 2 7 3 6 9 8 8 3]
 [1 8 4 9 8 0 8 2 9 3]
 [9 5 6 8 6 9 3 2 0 2]
 [7 3 6 2 6 8 4 3 3 5]]
----
Индекс 3
Строка [7 3 6 2 6 8 4 3 3 5]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [13]:
import numpy as np
arr1 = np.array([int(i) for i in (input().split())]) 
arr2 = np.array([int(i) for i in (input().split())])
d = np.sqrt(np.sum(np.square(arr1-arr2)))
print

0 0 0
1 1 1


<function print>

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [5]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B= np.array([[3, -1], [2, 1]])
C=np.array([[7, 21], [11, 8], [8, 4]])
AX = np.dot(C*(-1), np.linalg.inv(B))
X = np.dot(np.linalg.inv(A), AX)
print(np.around(X, decimals = 2))

[[ 1.  0.]
 [-2.  1.]
 [ 3. -4.]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [73]:
#понятно 
import numpy as np
#загрузка файла и его чтение
fail = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32',delimiter=',', skiprows = 1) #имя, тип данных, деление по , ; пропустить первую строчку
print(fail[:5])# срезами выводим первые 5 строк

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [74]:
#понятно
print('Среднее значение ', np.mean(fail[:,1:],0))
print('Минимальные значения ',np.min(fail[:,1:],0))
print('Максимальные значения ',np.max(fail[:,1:],0))
print('Медианы ',np.median(fail[:,1:],0))

Среднее значение  [2.16010017e+04 9.05528000e+00]
Минимальные значения  [0 1]
Максимальные значения  [2147483647         39]
Медианы  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [75]:
#квантиль-это вероятность, с которой значение не превышает максимум, в нашем случае эта вероятность равна 0.75 
M = np.quantile(fail[:,1], 0.75) #срез первого столбца
print(M)
print(fail[fail[:,1]<=M])

65.0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [76]:
a = np.count_nonzero(fail[:,1] == 0)           # выбрасываем строки , где не 0 и потом заменяем их на 1
fail[fail[:,1]==0] = 1                         # перебор строк в столбце 1
print(np.count_nonzero(fail[:,1] == 0))

0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [78]:
a = set((fail[:,0]))
print(len(a))

99522


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [57]:
a, number = np.unique(fail[:,2], return_counts=True)# unique- уникальный
print(np.column_stack((a, number)))

[[    1   492]
 [    2   924]
 [    3  2884]
 [    4  5479]
 [    5  7874]
 [    6  9328]
 [    7 10579]
 [    8 10887]
 [    9 10542]
 [   10  9548]
 [   11  8262]
 [   12  6574]
 [   13  4985]
 [   14  3639]
 [   15  2583]
 [   16  1760]
 [   17  1237]
 [   18   787]
 [   19   566]
 [   20   376]
 [   21   214]
 [   22   161]
 [   23   105]
 [   24    68]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [58]:
arr = fail[fail[:,2]<=5]
a = np.copy(arr)
print(a)
print('\n\n',fail)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [59]:
a = fail[:,2]/fail[:,1]#  делим 2 на 1 столбец
print( max(a))

23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [60]:
a = fail[:,1].argsort()# сортирует массив , но возвращает индексы, а не значени ямассива 
b = fail[a][-100:]
print(np.mean(b[:,2], axis = 0))# ср.знач 2 столбца 

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [61]:
a = np.random.randint(fail.shape[0], size = 10)# берем 10 рандомных значений и закидываем в массив.
print(fail[a])

[[ 58050     40      7]
 [182892    180     10]
 [165650     15      6]
 [169265     20      6]
 [270028     85     13]
 [376063   4335      6]
 [504600     30      8]
 [ 54057     35     15]
 [ 33323     15      7]
 [343529     23      8]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [62]:
a = np.mean(fail[:,2], axis = 0)
print(fail[fail[:,2]<a])# выводим 2 стобец , в котором уже все значения меньше среднего 
print('----')
print((100*len(fail[fail[:,2]<a]))/len(fail),'%')# ищем проценты, деля 2 строчку() на всю длину файла

[[ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]
----
58.989 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [49]:
a = np.append(fail, np.zeros((fail.shape[0],1), dtype = 'int32'), axis = 1)
a[np.logical_and(a[:,1]<=20,a[:,2]<=5)] = 1
a = a.copy()
print(a)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [     1      1      1      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [50]:
b = a[a[:,3] == 1]# создаем новый массив ,где есть 4 столбец, в котором простые и не простые рецепты
print((100*len(b)/len(fail)))# считаем проценты с этим столбцом 

9.943


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [81]:
a1 = fail[fail[:,1]<10]# короткие рецепты
a2 = fail[np.logical_and(fail[:,1]>=10, fail[:,1]<20)]#стандартные рецпеты
a3 = fail[fail[:,1]>=20]#длинные 
m = min(len(a1), len(a2), len(a3))
b = np.array([[a1[:m-1],a2[:m-1],a3[:m-1]]])
print(b.shape)
print(b)

(1, 3, 7587, 3)
[[[[ 67660      5      6]
   [366174      7      9]
   [204134      5      3]
   ...
   [     1      1      1]
   [420725      5      3]
   [     1      1      1]]

  [[ 94746     10      6]
   [ 33941     18      9]
   [446597     15      5]
   ...
   [107094     10      4]
   [  9831     15      7]
   [335859     12     14]]

  [[127244     60     16]
   [ 23891     25      7]
   [157911     60     14]
   ...
   [ 92137     80      9]
   [168901     25      7]
   [392339     35     13]]]]
